In [0]:
import pandas as pd
import numpy as np

In [0]:
data_all = pd.read_csv('/content/gdrive/My Drive/Multiagent/Data/split_data_all3.csv')

In [10]:
data_all.head()

,Unnamed: 0,usertag_10052,usertag_10006,usertag_13866,usertag_10110,usertag_10063,usertag_10111,usertag_10077,usertag_10057,usertag_10083,...,usertag_10140,usertag_10138,usertag_10142,usertag_13874,usertag_10130,usertag_10118,usertag_15398,os,browser,slotsize
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,windows,ie,200*200
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,windows,chrome,300*250
2,2,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,windows,ie,250*250
3,3,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,windows,ie,160*600
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,windows,ie,728*90

In [0]:
one = pd.get_dummies(data_all['os'],prefix = 'os')

In [0]:
data_all = data_all.join(one)

In [0]:
data_all = data_all.drop(columns = ['Unnamed: 0', 'os'])

In [16]:
data_all.head()

,usertag_10052,usertag_10006,usertag_13866,usertag_10110,usertag_10063,usertag_10111,usertag_10077,usertag_10057,usertag_10083,usertag_10024,...,usertag_10118,usertag_15398,browser,slotsize,os_android,os_ios,os_linux,os_mac,os_other,os_windows
0,0,0,0,0,0,0,0,0,0,0,...,0,0,ie,200*200,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,chrome,300*250,0,0,0,0,0,1
2,1,1,1,1,0,0,0,0,0,0,...,0,0,ie,250*250,0,0,0,0,0,1
3,0,0,1,0,1,1,0,0,0,0,...,0,0,ie,160*600,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,ie,728*90,0,0,0,0,0,1

In [0]:
one1 = pd.get_dummies(data_all['browser'],prefix = 'browser')
data_all = data_all.join(one1)
data_all = data_all.drop(columns= ['browser'])

In [18]:
data_all.head()

,usertag_10052,usertag_10006,usertag_13866,usertag_10110,usertag_10063,usertag_10111,usertag_10077,usertag_10057,usertag_10083,usertag_10024,...,os_windows,browser_chrome,browser_firefox,browser_ie,browser_maxthon,browser_opera,browser_other,browser_safari,browser_sogou,browser_theworld
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2,1,1,1,1,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,0,0,1,0,1,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

In [0]:
one1 = pd.get_dummies(data_all['slotsize'],prefix = 'slotsize')
data_all = data_all.join(one1)
data_all = data_all.drop(columns= ['slotsize'])

In [20]:
data_all.head()

,usertag_10052,usertag_10006,usertag_13866,usertag_10110,usertag_10063,usertag_10111,usertag_10077,usertag_10057,usertag_10083,usertag_10024,...,slotsize_620*60,slotsize_640*90,slotsize_728*90,slotsize_760*90,slotsize_910*90,slotsize_950*90,slotsize_960*60,slotsize_960*90,slotsize_980*80,slotsize_980*90
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [0]:
data_all.to_csv('/content/gdrive/My Drive/Multiagent/Data/split_data_all.csv', sep = ',')

In [0]:
asd = pd.read_csv('/content/gdrive/My Drive/Multiagent/Data/split_data_all.csv')

In [4]:
asd.head()

,Unnamed: 0,usertag_10052,usertag_10006,usertag_13866,usertag_10110,usertag_10063,usertag_10111,usertag_10077,usertag_10057,usertag_10083,...,slotsize_620*60,slotsize_640*90,slotsize_728*90,slotsize_760*90,slotsize_910*90,slotsize_950*90,slotsize_960*60,slotsize_960*90,slotsize_980*80,slotsize_980*90
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0